@host=http://localhost:5179

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Daniel",
    "lastName": "Pan",
    "email": "danielpan@gmail.com",
    "password": "password1"
}